name: mvp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15914824651554227
title: Muslim Voter Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3918463783338666
  lightness: 0.021811313927173615
  saturation: 0.24853184912353754
  rhythmicContrast: 0.8197591123171151
purpose: []
